artifact_uri: file:///Users/shubhamverma/Documents/DataScienceAndML/iNeuron/MLDL_Course/Sensor-fault-detection/sensor-fault-detection/sfd_project/mlruns/0/fd8452d49ddf4b6eaf67230c3fe472ea/artifacts
end_time: 1706269488305
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: fd8452d49ddf4b6eaf67230c3fe472ea
run_name: big-fox-629
run_uuid: fd8452d49ddf4b6eaf67230c3fe472ea
source_name: ''
source_type: 4
source_version: ''
start_time: 1706269488251
status: 3
tags: []
user_id: shubhamverma
