artifact_uri: file:///Users/shubhamverma/Documents/DataScienceAndML/iNeuron/MLDL_Course/Sensor-fault-detection/sensor-fault-detection/sfd_project/mlruns/0/42d78f5ac0d6480c83ca7fa4eb085c89/artifacts
end_time: 1706230972969
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 42d78f5ac0d6480c83ca7fa4eb085c89
run_name: wistful-pig-130
run_uuid: 42d78f5ac0d6480c83ca7fa4eb085c89
source_name: ''
source_type: 4
source_version: ''
start_time: 1706230972932
status: 3
tags: []
user_id: shubhamverma
