artifact_uri: file:///Users/shubhamverma/Documents/DataScienceAndML/iNeuron/MLDL_Course/Sensor-fault-detection/sensor-fault-detection/sfd_project/mlruns/0/497ec6483c9f4df794ec8df7f3ae5436/artifacts
end_time: 1706231316360
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 497ec6483c9f4df794ec8df7f3ae5436
run_name: upset-jay-285
run_uuid: 497ec6483c9f4df794ec8df7f3ae5436
source_name: ''
source_type: 4
source_version: ''
start_time: 1706231316320
status: 3
tags: []
user_id: shubhamverma
