artifact_location: file:///Users/shubhamverma/Documents/DataScienceAndML/iNeuron/MLDL_Course/Sensor-fault-detection/sensor-fault-detection/sfd_project/mlruns/0
creation_time: 1706230583155
experiment_id: '0'
last_update_time: 1706230583155
lifecycle_stage: active
name: Default
