artifact_uri: file:///Users/shubhamverma/Documents/DataScienceAndML/iNeuron/MLDL_Course/Sensor-fault-detection/sensor-fault-detection/sfd_project/mlruns/0/d0439560b3fa4c56a3c19c2241503413/artifacts
end_time: 1706230717263
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d0439560b3fa4c56a3c19c2241503413
run_name: traveling-lynx-328
run_uuid: d0439560b3fa4c56a3c19c2241503413
source_name: ''
source_type: 4
source_version: ''
start_time: 1706230717217
status: 3
tags: []
user_id: shubhamverma
