artifact_uri: file:///Users/shubhamverma/Documents/DataScienceAndML/iNeuron/MLDL_Course/Sensor-fault-detection/sensor-fault-detection/sfd_project/mlruns/0/275f706e9fa046df9f2f7cad5561bbe2/artifacts
end_time: 1706230583400
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 275f706e9fa046df9f2f7cad5561bbe2
run_name: persistent-lynx-14
run_uuid: 275f706e9fa046df9f2f7cad5561bbe2
source_name: ''
source_type: 4
source_version: ''
start_time: 1706230583364
status: 3
tags: []
user_id: shubhamverma
