artifact_uri: file:///Users/shubhamverma/Documents/DataScienceAndML/iNeuron/MLDL_Course/Sensor-fault-detection/sensor-fault-detection/sfd_project/mlruns/0/37157daad2d24ac1bcc19ed531c2099f/artifacts
end_time: 1706232072630
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 37157daad2d24ac1bcc19ed531c2099f
run_name: burly-snipe-410
run_uuid: 37157daad2d24ac1bcc19ed531c2099f
source_name: ''
source_type: 4
source_version: ''
start_time: 1706232072594
status: 3
tags: []
user_id: shubhamverma
