artifact_uri: file:///Users/shubhamverma/Documents/DataScienceAndML/iNeuron/MLDL_Course/Sensor-fault-detection/sensor-fault-detection/sfd_project/mlruns/0/9de27bb4fb1e4bbba490a04d12aa8dc1/artifacts
end_time: 1706231182899
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9de27bb4fb1e4bbba490a04d12aa8dc1
run_name: brawny-kite-288
run_uuid: 9de27bb4fb1e4bbba490a04d12aa8dc1
source_name: ''
source_type: 4
source_version: ''
start_time: 1706231182859
status: 3
tags: []
user_id: shubhamverma
