artifact_uri: file:///Users/shubhamverma/Documents/DataScienceAndML/iNeuron/MLDL_Course/Sensor-fault-detection/sensor-fault-detection/sfd_project/mlruns/0/bee62dce68cf4491b5621dd0495b27ca/artifacts
end_time: 1706231544689
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bee62dce68cf4491b5621dd0495b27ca
run_name: angry-donkey-513
run_uuid: bee62dce68cf4491b5621dd0495b27ca
source_name: ''
source_type: 4
source_version: ''
start_time: 1706231544655
status: 3
tags: []
user_id: shubhamverma
